version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: 'db'
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nest_learn
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    expose:
      - 5432

  app:
    image: node:22.4.1
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3000:3000
    command: bash -c "yarn install && prisma migrate dev --schema=./src/prisma/schema.prisma && yarn db:generate && yarn build && yarn start:prod"

volumes:
  pgdata:
